"""create interest

Revision ID: 0bab90840c30
Revises: e9ca2590a593
Create Date: 2025-05-28 09:59:41.125042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0bab90840c30'
down_revision = 'e9ca2590a593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column(
            'content',
            existing_type=sa.TEXT(),
            type_=postgresql.JSON(astext_type=sa.Text()),
            nullable=False,
            postgresql_using="content::json"
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
