"""add description column to auto task table

Revision ID: 18287dc0ea5f
Revises: cecb104a4abe
Create Date: 2025-06-02 14:11:55.219206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18287dc0ea5f'
down_revision = 'cecb104a4abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_task', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
