"""remove article type column

Revision ID: 193a778eeb70
Revises: 8ac19663e449
Create Date: 2025-06-09 12:31:26.614112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '193a778eeb70'
down_revision = '8ac19663e449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insight_article', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insight_article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', postgresql.ENUM('chat', 'report', name='article_type'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
