"""add colums in message table

Revision ID: 21edbd66ff44
Revises: 18287dc0ea5f
Create Date: 2025-06-04 11:50:35.991645

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = '21edbd66ff44'
down_revision = '18287dc0ea5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keyword_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('keyword_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('keyword_vector')
        batch_op.drop_column('keyword_text')

    # ### end Alembic commands ###
