"""Fix Message role

Revision ID: 2b58fcff4c3d
Revises: 8f6caca2e5fd
Create Date: 2025-05-20 17:15:33.882484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b58fcff4c3d'
down_revision = '8f6caca2e5fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('tool')

    # ### end Alembic commands ###
