"""create auto task auto task step

Revision ID: 2df112e66bb2
Revises: 9166dcb99c44
Create Date: 2025-06-06 15:11:31.104299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2df112e66bb2'
down_revision = '9166dcb99c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_task_step',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auto_task_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('depends_on', sa.JSON(), nullable=True),
    sa.Column('tool', sa.Text(), nullable=True),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['auto_task_id'], ['auto_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auto_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('repeat', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('start_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('finish_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('preferred_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('task_list', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tool', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('linked_service', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('current_step', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('output', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('meta', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_task', schema=None) as batch_op:
        batch_op.drop_column('meta')
        batch_op.drop_column('output')
        batch_op.drop_column('status')
        batch_op.drop_column('current_step')
        batch_op.drop_column('linked_service')
        batch_op.drop_column('tool')
        batch_op.drop_column('task_list')
        batch_op.drop_column('active')
        batch_op.drop_column('preferred_at')
        batch_op.drop_column('finish_at')
        batch_op.drop_column('start_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('repeat')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    op.drop_table('auto_task_step')
    # ### end Alembic commands ###
