"""Fix Message role

Revision ID: 38911eb1d7e9
Revises: 2b58fcff4c3d
Create Date: 2025-05-20 17:16:34.821024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38911eb1d7e9'
down_revision = '2b58fcff4c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('tool')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
