"""remove unique name

Revision ID: 4dcd819f29fe
Revises: 193a778eeb70
Create Date: 2025-06-09 18:07:45.530212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dcd819f29fe'
down_revision = '193a778eeb70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_username_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_username_key', ['username'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
