"""update auto task start finish linked

Revision ID: 55b30aea6f8c
Revises: 156d3e924b9f
Create Date: 2025-06-01 16:45:03.899194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '55b30aea6f8c'
down_revision = '156d3e924b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_task', schema=None) as batch_op:
        batch_op.alter_column('start_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('finish_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('linked_service',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_task', schema=None) as batch_op:
        batch_op.alter_column('linked_service',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('finish_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.alter_column('start_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    # ### end Alembic commands ###
