"""interest fix

Revision ID: 758ce996c984
Revises: ee82416bbd64
Create Date: 2025-05-28 17:18:21.984248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '758ce996c984'
down_revision = 'ee82416bbd64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('importance', sa.Float(), nullable=False))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))

    with op.batch_alter_table('interest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.drop_column('importance')

    # ### end Alembic commands ###
