"""add script column to briefing

Revision ID: 8ac19663e449
Revises: 2df112e66bb2
Create Date: 2025-06-08 13:57:55.067389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac19663e449'
down_revision = '2df112e66bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('briefing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('script', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('briefing', schema=None) as batch_op:
        batch_op.drop_column('script')

    # ### end Alembic commands ###
