"""메타데이터 추가

Revision ID: abb4e2a4df9b
Revises: 38911eb1d7e9
Create Date: 2025-05-24 19:46:49.876517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb4e2a4df9b'
down_revision = '38911eb1d7e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_metadata', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('message_metadata')

    # ### end Alembic commands ###
