"""add user column

Revision ID: c6087163ce39
Revises: caafbb85c4aa
Create Date: 2025-05-31 16:11:17.212586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6087163ce39'
down_revision = 'caafbb85c4aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint('report_schedule_id_fkey', type_='foreignkey')
        batch_op.drop_column('schedule_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_memory', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_memory')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('report_schedule_id_fkey', 'schedule', ['schedule_id'], ['id'])

    # ### end Alembic commands ###
