"""insight_article column fix

Revision ID: caafbb85c4aa
Revises: a7a22f5d2abb
Create Date: 2025-05-29 14:26:37.127140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caafbb85c4aa'
down_revision = 'a7a22f5d2abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insight_article', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False,
               postgresql_using="content::json"
               )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insight_article', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
