"""add task_list column to auto_task

Revision ID: cecb104a4abe
Revises: 55b30aea6f8c
Create Date: 2025-06-02 12:07:25.313702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cecb104a4abe'
down_revision = '55b30aea6f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_list', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_task', schema=None) as batch_op:
        batch_op.drop_column('task_list')

    # ### end Alembic commands ###
