"""update insight article table

Revision ID: e45c40b2ca95
Revises: 4c38e73b9494
Create Date: 2025-05-28 22:20:10.895541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45c40b2ca95'
down_revision = '4c38e73b9494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insight_article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('type', sa.Enum('chat', 'report', name='article_type'), nullable=False))
        batch_op.add_column(sa.Column('keywords', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('interest_ids', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insight_article', schema=None) as batch_op:
        batch_op.drop_column('interest_ids')
        batch_op.drop_column('keywords')
        batch_op.drop_column('type')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
