"""Add timestamp column to schedule

Revision ID: ee82416bbd64
Revises: 0b25b9753e8b
Create Date: 2025-05-28 16:14:21.452665

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime
from sqlalchemy.sql import table, column
from sqlalchemy import DateTime


# revision identifiers, used by Alembic.
revision = 'ee82416bbd64'
down_revision = '0b25b9753e8b'
branch_labels = None
depends_on = None


def upgrade():
    # 1. nullable=True로 컬럼 추가
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False))

    # 2. 기존 row에 대해 현재 UTC 시간으로 값 채우기
    schedule = table('schedule',
        column('timestamp', DateTime(timezone=True))
    )
    op.execute(
        sa.text("UPDATE schedule SET timestamp = NOW() WHERE timestamp IS NULL")
    )

    # 3. NOT NULL로 변경
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('timestamp', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
