# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - seobi-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   env:
  #     FLASK_APP: app
  #     FLASK_ENV: testing
  #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  #     # 테스트용 데이터베이스 접속 정보
  #     PGPASSWORD: ${{ secrets.TEST_PGPASSWORD }}

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Python version
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.12'

  #     - name: Install uv
  #       run: |
  #         curl -LsSf https://astral.sh/uv/install.sh | sh
  #         echo "$HOME/.cargo/bin" >> $GITHUB_PATH

  #     - name: Create and start virtual environment
  #       run: |
  #         uv venv
  #         source .venv/bin/activate
      
  #     - name: Install dependencies
  #       run: |
  #         source .venv/bin/activate
  #         uv add -r requirements.txt
  #         uv add pytest pytest-cov

  #     - name: Run tests
  #       run: |
  #         source .venv/bin/activate
  #         pytest tests/ -v --cov=app

  build:
    # needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create and start virtual environment
        run: |
          uv venv
          source .venv/bin/activate
      
      - name: Install dependencies
        run: |
          source .venv/bin/activate
          uv add -r requirements.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !.venv/

  deploy:
    runs-on: ubuntu-latest
    # needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BBAB0F361FDA43C1B4376933ED75D1C5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FB9EAA41DABA41D29AD25B07B6C83945 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C0861A7203604D68AB663E67494A9D9F }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'seobi-backend'
          slot-name: 'Production'
          
